from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
MAX_INT32 = (1 << 31) - 1
MAX_UINT32 = (1 << 32) - 1
BYTES_PER_LINE = 16


@dataclass(frozen=True)
class Icon:
    name: str
    data: bytes
    offset: int


def collect_icons(input_directory: Path) -> list[Icon]:
    paths = sorted(input_directory.glob("*.png"), key=lambda path: path.stem)
    if not paths:
        raise ValueError(f'No PNG icons found in "{input_directory}".')

    names_by_casefold: dict[str, str] = {}
    icons: list[Icon] = []
    offset = 0

    for path in paths:
        name = path.stem
        folded_name = name.casefold()
        previous_name = names_by_casefold.get(folded_name)
        if previous_name is not None:
            raise ValueError(f'Icon names differ only by case: "{previous_name}" and "{name}".')
        names_by_casefold[folded_name] = name

        data = path.read_bytes()
        if not data.startswith(PNG_SIGNATURE):
            raise ValueError(f'Invalid PNG signature: "{path.name}".')
        if len(data) > MAX_INT32:
            raise ValueError(f'PNG is too large for stb_image: "{path.name}" ({len(data)} bytes).')
        if offset + len(data) > MAX_UINT32:
            raise ValueError("Combined PNG data exceeds the uint32_t offset range.")

        icons.append(Icon(name=name, data=data, offset=offset))
        offset += len(data)

    return icons


def generate_header(icons: list[Icon]) -> bytes:
    lines = [
        "#pragma once",
        "",
        "// This file is generated by GenerateBuiltinIcons.py. Do not edit it manually.",
        "",
        "#include <algorithm>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <iterator>",
        "#include <string_view>",
        "",
        "namespace BuiltinIcons",
        "{",
        "struct IconData",
        "{",
        "\tuint8_t const* m_data = nullptr;",
        "\tsize_t         m_size = 0;",
        "",
        "\texplicit operator bool() const { return m_data != nullptr; }",
        "};",
        "",
        "namespace Detail",
        "{",
        "struct IconEntry",
        "{",
        "\tstd::string_view m_name;",
        "\tuint32_t         m_offset;",
        "\tuint32_t         m_size;",
        "};",
        "",
        "inline constexpr uint8_t kData[] =",
        "{",
    ]

    combined_data = b"".join(icon.data for icon in icons)
    for start in range(0, len(combined_data), BYTES_PER_LINE):
        chunk = combined_data[start : start + BYTES_PER_LINE]
        lines.append("\t" + ", ".join(f"0x{value:02x}" for value in chunk) + ",")

    lines.extend(
        [
            "};",
            "",
            "inline constexpr IconEntry kEntries[] =",
            "{",
        ]
    )

    for icon in icons:
        name_literal = json.dumps(icon.name, ensure_ascii=True)
        lines.append(f"\t{{ {name_literal}, {icon.offset}u, {len(icon.data)}u }},")

    lines.extend(
        [
            "};",
            "} // namespace Detail",
            "",
            "inline IconData Find(std::string_view iconName)",
            "{",
            "\tauto const begin = std::begin(Detail::kEntries);",
            "\tauto const end   = std::end(Detail::kEntries);",
            "\tauto const found = std::lower_bound(",
            "\t\tbegin, end, iconName, [](Detail::IconEntry const& entry, std::string_view value)",
            "\t\t{",
            "\t\t\treturn entry.m_name < value;",
            "\t\t});",
            "",
            "\tif (found == end || found->m_name != iconName)",
            "\t{",
            "\t\treturn {};",
            "\t}",
            "",
            "\treturn { Detail::kData + found->m_offset, found->m_size };",
            "}",
            "} // namespace BuiltinIcons",
            "",
        ]
    )

    return "\r\n".join(lines).encode("utf-8")


def write_if_changed(output_path: Path, content: bytes) -> bool:
    if output_path.exists() and output_path.read_bytes() == content:
        return False

    output_path.write_bytes(content)
    return True


def main() -> None:
    icon_directory = Path(__file__).resolve().parent
    output_path = icon_directory / "BuiltinIcons.hpp"

    try:
        icons = collect_icons(icon_directory)
        content = generate_header(icons)
        changed = write_if_changed(output_path, content)
    except (OSError, ValueError) as error:
        raise SystemExit(f"error: {error}") from error

    total_bytes = sum(len(icon.data) for icon in icons)
    action = "Generated" if changed else "Unchanged"
    print(f"{action} {output_path.name}: {len(icons)} icons, {total_bytes} bytes.")


if __name__ == "__main__":
    main()
