<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildProjectDirectory)/.ming/dotnet/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)/.ming/dotnet/obj/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <DefaultItemExcludes>$(DefaultItemExcludes);.ming/**;bin/**;obj/**</DefaultItemExcludes>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
</Project>