<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="DeployManagedRuntime" AfterTargets="Build">
    <Exec Command="xcopy /Y /F /I /E &quot;$(TargetDir)*&quot; &quot;$(MSBuildProjectDirectory)\..\..\..\Run\MingSharp\Api\&quot;" />
  </Target>

</Project>
